### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by 112madgamer** [DylanHamer/HackWM#2]
On running python3 HackWM.py, I am getting this error

`Traceback (most recent call last):
  File "HackWM.py", line 13, in <module>
    from Mouse import mouse
  File "/home/doom/Desktop/HackWM/Mouse.py", line 31
    elif event.detail == 2 and event.type == X.ButtonPress:
                                                          ^
TabError: inconsistent use of tabs and spaces in indentation
`

Am I missing a module or is the code in the repo none working? Will there be updates soon?

**Comment by DylanHamer** [comment]
Oops! I must have accidentally messed up the indentation. Will get it
sorted soon.

**Comment by 112madgamer** [comment]
I fixed the indentation error. I am running the WM on when I use the bind ALT+T I see the log show that the terminal has been executed but the window doesn't appear?
